FROM postgres:13.6

RUN localedef -A/usr/share/locale/locale.alias -ija_JP -fUTF-8 ja_JP.UTF-8
# docker login -u justincasedev
# docker build -t justincasetech/postgres:13.6-stretch .
# docker push justincasetech/postgres:13.6-stretch
