FROM amazonlinux:2.0.20191217.0
# install git and openssh due to error `Either git or ssh (required by git to clone through SSH) is not installed in the image.`
RUN yum install -y awscli-1.16.300 git openssh
