FROM python:3.9.13-alpine3.16

RUN pip install --upgrade pip;\
    pip install --upgrade awscli;

RUN set -e;\
    apk add --no-cache nodejs git=2.36.2-r0 openssh=9.0_p1-r1;\
    apk add --no-cache npm;\
    npm c set unsafe-perm true;\
    npm i -g aws-cdk@2.31.1;\
