FROM postgres:12.10

RUN localedef -A/usr/share/locale/locale.alias -ija_JP -fUTF-8 ja_JP.UTF-8
# docker login -u justincasedev
# docker build -t justincasetech/postgres:12.10-stretch .
# docker push justincasetech/postgres:12.10-stretch
